live:
  - name: Polygon
    networks:
      - chainid: 137
        explorer: https://polygonscan.com/
        host: https://polygon-mainnet.g.alchemy.com/v2/$ALCHEMY_PROJECT_TOKEN_ID
        id: poly-mainnet-alchemy
        multicall2: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696"
        name: Polygon Mainnet (alchemy)
